from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List


@dataclass
class FilterRules:
    job_source_domains: List[str] = field(default_factory=list)
    non_job_domains: List[str] = field(default_factory=list)
    job_keywords: List[str] = field(default_factory=list)
    role_title_patterns: List[str] = field(default_factory=list)
    promo_negative_patterns: List[str] = field(default_factory=list)
    edu_negative_patterns: List[str] = field(default_factory=list)
    strong_job_signal_patterns: List[str] = field(default_factory=list)
    interview_context_patterns: List[str] = field(default_factory=list)
    oa_assessment_patterns: List[str] = field(default_factory=list)
    # New fields for enhanced filtering
    promotional_sender_patterns: List[str] = field(default_factory=list)
    commercial_domain_patterns: List[str] = field(default_factory=list)
    weak_job_keywords: List[str] = field(default_factory=list)
    transactional_patterns: List[str] = field(default_factory=list)
    marketing_footer_patterns: List[str] = field(default_factory=list)

    @classmethod
    def default(cls) -> "FilterRules":
        return cls(
            job_source_domains=[
                "greenhouse.io",
                "lever.co",
                "workable.com",
                "icims.com",
                "ashbyhq.com",
                "smartrecruiters.com",
                "myworkday.com",
                "jobvite.com",
                "linkedin.com",
                "indeed.com",
                "glassdoor.com",
            ],
            non_job_domains=[
                # Airlines / Travel
                "e.allegiant.com",
                "t.southwest.com",
                "em.united.com",
                "em.aa.com",
                "mail.delta.com",
                "em.jetblue.com",
                "e.spirit.com",
                "em.alaskaair.com",
                "email.hotels.com",
                "e.booking.com",
                "e.expedia.com",
                "email.priceline.com",
                "e.tripadvisor.com",
                "e.vrbo.com",
                "em.airbnb.com",
                # Social / Entertainment
                "email.meetup.com",
                "announcements.soundcloud.com",
                "info.spotify.com",
                "em.pandora.com",
                "mail.netflix.com",
                "em.hulu.com",
                "email.disneyplus.com",
                "mail.hbomax.com",
                "em.peacocktv.com",
                "mail.paramountplus.com",
                "e.twitch.tv",
                "em.discord.com",
                "em.slack.com",
                "marketing.zoom.us",
                # Telecom
                "emaildl.att-mail.com",
                "vtext.com",
                "email.t-mobile.com",
                "e.vzw.com",
                "e.xfinity.com",
                "e.spectrum.net",
                "em.cox.com",
                # Education marketing
                "sfmc2.edx.org",
                "email.coursera.org",
                "em.udemy.com",
                "mail.skillshare.com",
                "e.udacity.com",
                "em.linkedin.com",
                "mail.masterclass.com",
                # Banking / Finance
                "email.chime.com",
                "e.chime.com",
                "member.chime.com",
                "alert.chime.com",
                "fidelity.com",
                "e.fidelity.com",
                "mail.fidelity.com",
                "em.schwab.com",
                "e.schwab.com",
                "email.etrade.com",
                "e.vanguard.com",
                "mail.tdameritrade.com",
                "em.robinhood.com",
                "em.coinbase.com",
                "mail.binance.com",
                "e.paypal.com",
                "em.venmo.com",
                "em.cashapp.com",
                "em.zelle.com",
                "info.capitalone.com",
                "em.capitalone.com",
                "mail.chase.com",
                "em.chase.com",
                "alerts.chase.com",
                "email.bankofamerica.com",
                "em.wellsfargo.com",
                "alerts.wellsfargo.com",
                "em.citi.com",
                "alerts.citi.com",
                "mail.discover.com",
                "em.discover.com",
                "alerts.discover.com",
                "em.amex.com",
                "alerts.americanexpress.com",
                "em.ally.com",
                "mail.marcus.com",
                "em.sofi.com",
                "em.affirm.com",
                "em.klarna.com",
                "em.afterpay.com",
                "em.creditkarma.com",
                "mail.mint.com",
                "em.nerdwallet.com",
                "mail.betterment.com",
                "em.wealthfront.com",
                "em.acorns.com",
                # Food / Restaurants
                "info.papajohns.com",
                "e.papajohns.com",
                "marketing.papajohns.com",
                "em.dominos.com",
                "info.pizzahut.com",
                "em.chipotle.com",
                "e.tacobell.com",
                "em.mcdonalds.com",
                "em.burgerking.com",
                "em.wendys.com",
                "em.subway.com",
                "em.chick-fil-a.com",
                "em.starbucks.com",
                "em.dunkindonuts.com",
                "em.doordash.com",
                "em.ubereats.com",
                "em.grubhub.com",
                "em.postmates.com",
                "em.instacart.com",
                "em.gopuff.com",
                "em.seamless.com",
                # E-commerce / Retail
                "zzounds.com",
                "em.zzounds.com",
                "marketing.zzounds.com",
                "email.amazon.com",
                "marketing.amazon.com",
                "ship-confirm.amazon.com",
                "em.ebay.com",
                "messages.ebay.com",
                "em.walmart.com",
                "em.target.com",
                "em.bestbuy.com",
                "em.costco.com",
                "em.samsclub.com",
                "em.kroger.com",
                "em.safeway.com",
                "em.wholefoods.com",
                "em.traderjoes.com",
                "em.homedepot.com",
                "em.lowes.com",
                "em.menards.com",
                "em.ikea.com",
                "em.wayfair.com",
                "em.overstock.com",
                "em.bedbathandbeyond.com",
                "em.kohls.com",
                "em.macys.com",
                "em.nordstrom.com",
                "em.bloomingdales.com",
                "em.neimanmarcus.com",
                "em.saks.com",
                "em.jcpenney.com",
                "em.dillards.com",
                "em.belk.com",
                "em.oldnavy.com",
                "em.gap.com",
                "em.bananarepublic.com",
                "em.athleta.com",
                "em.hm.com",
                "em.zara.com",
                "em.uniqlo.com",
                "em.forever21.com",
                "em.urbanoutfitters.com",
                "em.anthropologie.com",
                "em.freepeople.com",
                "em.ae.com",
                "em.aerie.com",
                "em.abercrombie.com",
                "em.hollister.com",
                "em.express.com",
                "em.nike.com",
                "em.adidas.com",
                "em.underarmour.com",
                "em.footlocker.com",
                "em.dickssportinggoods.com",
                "em.rei.com",
                "em.patagonia.com",
                "em.thenorthface.com",
                "em.lululemon.com",
                "em.sephora.com",
                "em.ulta.com",
                "em.bathandbodyworks.com",
                "em.victoriassecret.com",
                "em.etsy.com",
                "em.wish.com",
                "em.aliexpress.com",
                "em.shein.com",
                "em.temu.com",
                "em.shopify.com",
                "em.squarespace.com",
                "em.wix.com",
                "em.bigcommerce.com",
                # Tech companies (marketing)
                "team.twilio.com",
                "marketing.twilio.com",
                "info.twilio.com",
                "em.twilio.com",
                "marketing.github.com",
                "em.github.com",
                "noreply.github.com",
                "marketing.gitlab.com",
                "em.gitlab.com",
                "marketing.atlassian.com",
                "em.atlassian.com",
                "marketing.salesforce.com",
                "em.salesforce.com",
                "marketing.hubspot.com",
                "em.hubspot.com",
                "marketing.mailchimp.com",
                "em.mailchimp.com",
                "marketing.sendgrid.com",
                "em.sendgrid.com",
                "em.dropbox.com",
                "em.box.com",
                "em.google.com",
                "em.microsoft.com",
                "em.apple.com",
                "em.adobe.com",
                "em.autodesk.com",
                "em.oracle.com",
                "em.sap.com",
                "em.ibm.com",
                "em.dell.com",
                "em.hp.com",
                "em.lenovo.com",
                "em.samsung.com",
                "em.lg.com",
                "em.sony.com",
                "marketing.aws.amazon.com",
                "em.digitalocean.com",
                "em.heroku.com",
                "em.cloudflare.com",
                "em.godaddy.com",
                "em.namecheap.com",
                "em.bluehost.com",
                "em.hostgator.com",
                "em.siteground.com",
                # Newsletters / Media
                "em.substack.com",
                "em.medium.com",
                "em.wordpress.com",
                "em.blogger.com",
                "em.nytimes.com",
                "em.wsj.com",
                "em.washingtonpost.com",
                "em.cnn.com",
                "em.foxnews.com",
                "em.bbc.com",
                "em.theguardian.com",
                "em.huffpost.com",
                "em.buzzfeed.com",
                "em.vice.com",
                "em.vox.com",
                "em.wired.com",
                "em.techcrunch.com",
                "em.theverge.com",
                "em.engadget.com",
                "em.arstechnica.com",
                "em.gizmodo.com",
                "em.mashable.com",
                "em.cnet.com",
                "em.zdnet.com",
                # Health / Fitness
                "em.fitbit.com",
                "em.myfitnesspal.com",
                "em.peloton.com",
                "em.orangetheory.com",
                "em.planetfitness.com",
                "em.24hourfitness.com",
                "em.goldsgym.com",
                "em.equinox.com",
                "em.noom.com",
                "em.weightwatchers.com",
                "em.headspace.com",
                "em.calm.com",
                "em.cvs.com",
                "em.walgreens.com",
                "em.riteaid.com",
                "em.healthline.com",
                "em.webmd.com",
                # Insurance
                "em.geico.com",
                "em.progressive.com",
                "em.statefarm.com",
                "em.allstate.com",
                "em.nationwide.com",
                "em.farmers.com",
                "em.libertymutual.com",
                "em.usaa.com",
                "em.travelers.com",
                "em.lemonade.com",
                # Auto
                "em.carmax.com",
                "em.carvana.com",
                "em.vroom.com",
                "em.autotrader.com",
                "em.cargurus.com",
                "em.cars.com",
                "em.truecar.com",
                "em.kbb.com",
                "em.edmunds.com",
                # Real Estate
                "em.zillow.com",
                "em.trulia.com",
                "em.redfin.com",
                "em.realtor.com",
                "em.apartments.com",
                "em.rent.com",
                # Utilities / Services
                "em.nextdoor.com",
                "em.yelp.com",
                "em.angi.com",
                "em.thumbtack.com",
                "em.taskrabbit.com",
                # Gaming
                "em.steam.com",
                "em.epicgames.com",
                "em.riotgames.com",
                "em.blizzard.com",
                "em.ea.com",
                "em.ubisoft.com",
                "em.playstation.com",
                "em.xbox.com",
                "em.nintendo.com",
            ],
            job_keywords=[
                # These are the "strong" job keywords that carry more weight
                "recruiter",
                "recruiting",
                "talent acquisition",
                "talent partner",
                "sourcer",
                "are you open to",
                "are you interested",
                "would you be interested",
                "calendar link",
                "job description",
                "offer letter",
                "base salary",
                "equity",
                "rsu",
                "relocation",
                "visa sponsorship",
                "background check",
                "candidacy",
                "resume",
                "cv",
                "portfolio",
                "cover letter",
                "phone screen",
                "interview loop",
                "take-home",
                "coding challenge",
                "technical screen",
                "onsite",
                "final round",
                "time slots",
                "internship",
                "co-op",
                "apprenticeship",
                "new grad",
                "job alert",
                "jobs you may like",
                "new jobs",
                "recommended jobs",
                "saved job",
                "application status",
                "your application",
                "no longer under consideration",
                "we decided to move forward",
                "thank you for applying",
            ],
            weak_job_keywords=[
                # These are ambiguous and require additional context
                "opportunity",
                "role",
                "position",
                "opening",
                "vacancy",
                "quick chat",
                "jd",
                "responsibilities",
                "requirements",
                "offer",
                "compensation",
                "bonus",
                "benefits",
                "sponsorship",
                "start date",
                "application",
                "applied",
                "candidate",
                "submission",
                "screening",
                "interview",
                "assignment",
                "assessment",
                "next steps",
                "graduate program",
            ],
            role_title_patterns=[
                r"\bsoftware engineer\b",
                r"\bdeveloper\b",
                r"\bdata scientist\b",
                r"\bnlp\b",
                r"\bml engineer\b|\bmachine learning\b",
                r"\bproduct manager\b",
                r"\bproject manager\b",
                r"\bdevops\b",
                r"\bsite reliability\b|\bsre\b",
                r"\bsecurity engineer\b",
                r"\bsolutions engineer\b",
                r"\bsales engineer\b",
                r"\baccount executive\b",
                r"\bsdr\b|\bbdr\b",
                r"\bsales ops\b",
                r"\bsalesforce\b",
                r"\bcustomer success\b",
                r"\bprincipal\b|\bstaff\b|\bsenior\b|\bjunior\b",
                r"\banalyst\b",
                r"\binternship\b",
                r"\bintern\b(?!et)\b",
            ],
            promo_negative_patterns=[
                r"\bfree shipping\b",
                r"\bpromo code\b",
                r"\bcoupon\b",
                r"\bdiscount\b",
                r"\bclearance\b",
                r"\bflash sale\b",
                r"\border (confirmed|confirmation)\b",
                r"\bshipping (update|notification)\b",
                r"\bdelivered\b",
                r"\btracking number\b",
                r"\byour cart\b",
                r"\bnewsletter\b",
                r"\bunsubscribe\b",
                r"\byour (online )?bill\b",
                r"\bbill is ready\b",
                r"\bpayment due\b",
                r"\baccount number\b",
                # Enhanced promotional patterns
                r"\bshop now\b",
                r"\bbuy now\b",
                r"\border now\b",
                r"\blimited time\b",
                r"\bexclusive offer\b",
                r"\bspecial offer\b",
                r"\bdeal of the day\b",
                r"\bsave \d+%\b",
                r"\b\d+% off\b",
                r"\bfree gift\b",
                r"\bgift card\b",
                r"\breward(s)? point\b",
                r"\bcashback\b",
                r"\bearn \$?\d+\b",
                r"\brefer a friend\b",
                r"\breferral bonus\b",
                r"\bloyalty program\b",
                r"\bsubscription (renewal|expire|cancel)\b",
                r"\bmembership (renewal|expire|cancel)\b",
                r"\bauto-?renew\b",
                r"\bprice drop\b",
                r"\bback in stock\b",
                r"\bitems? in your (cart|wishlist)\b",
                r"\babandoned cart\b",
                r"\bcomplete your (order|purchase)\b",
                r"\bwe miss you\b",
                r"\bcome back\b",
                r"\bseasonal sale\b",
                r"\bholiday (sale|special|deal)\b",
                r"\bblack friday\b",
                r"\bcyber monday\b",
                r"\bprime day\b",
                r"\blearning path\b",
                r"\bcourse recommendation\b",
            ],
            edu_negative_patterns=[
                r"\badmissions?\b",
                r"\bapply(ing|)\b.*\b(program|degree|master|ms|m\.s\.|mba|certificate)\b",
                r"\bonline master\b",
                r"\buniversity\b",
                r"\bschool of\b",
                r"\bberkeley\b",
                r"\bedx\b",
                r"\btuition\b",
                r"\benroll\b",
                r"\bgraduate program\b",
            ],
            strong_job_signal_patterns=[
                r"\boffer letter\b",
                r"\bphone screen\b",
                r"\btechnical screen\b",
                r"\bonsite\b",
                r"\bfinal round\b",
                r"\brecruit(er|ing)\b",
                r"\btalent acquisition\b",
                r"\bsourcer\b",
                r"\bapplication (received|submitted|status)\b",
                r"\bbackground check\b",
                r"\bjob description\b",
                r"\bbase salary\b",
                r"\bequity\b|\brsu\b",
                r"\binternship\b|\bintern\b(?!et)\b|\bco-?op\b|\bapprenticeship\b",
                r"\bschedule.{0,20}interview\b",
                r"\binterview.{0,20}schedule\b",
                r"\bcoding challenge\b|\bcoding test\b|\btechnical assessment\b",
                r"\bhiring manager\b",
                r"\bteam (is |would |like to )?meet\b",
                r"\bmeet the team\b",
                r"\bwe('d| would) like to (move forward|proceed)\b",
                r"\bnext (step|stage|round)\b",
                r"\byour candidacy\b",
                r"\byour resume\b",
                r"\byour profile\b",
                r"\bjob opportunity\b",
                r"\bcareer opportunity\b",
            ],
            interview_context_patterns=[
                r"\binterview\b",
                r"\bphone screen\b",
                r"\btechnical screen\b",
                r"\bonsite\b",
                r"\bfinal round\b",
                r"\brecruit(er|ing)\b",
                r"\btalent acquisition\b",
            ],
            oa_assessment_patterns=[
                r"\b(online assessment|assessment|coding challenge|take[- ]home|hacker(rank)?|codesignal|codility|karat)\b",
            ],
            promotional_sender_patterns=[
                r"^noreply@",
                r"^no-reply@",
                r"^donotreply@",
                r"^do-not-reply@",
                r"^marketing@",
                r"^promo@",
                r"^promotions@",
                r"^newsletter@",
                r"^news@",
                r"^updates@",
                r"^info@",
                r"^support@",
                r"^help@",
                r"^team@",
                r"^hello@",
                r"^hi@",
                r"^contact@",
                r"^sales@",
                r"^billing@",
                r"^accounts?@",
                r"^notifications?@",
                r"^alerts?@",
                r"^mailer@",
                r"^mail@",
                r"^message@",
                r"^email@",
                r"^e-?news@",
                r"^announce@",
                r"^store@",
                r"^shop@",
                r"^orders?@",
                r"^shipping@",
                r"^delivery@",
                r"^rewards?@",
                r"^loyalty@",
                r"^member(ship)?@",
                r"^customer@",
                r"^service@",
                r"^feedback@",
                r"^survey@",
            ],
            commercial_domain_patterns=[
                # Patterns to catch commercial sender subdomains
                r"^e\.",
                r"^em\.",
                r"^email\.",
                r"^mail\.",
                r"^marketing\.",
                r"^promo\.",
                r"^newsletter\.",
                r"^info\.",
                r"^news\.",
                r"^updates?\.",
                r"^notifications?\.",
                r"^alerts?\.",
                r"^shop\.",
                r"^store\.",
                r"^orders?\.",
                r"^shipping\.",
                r"^delivery\.",
                r"^tracking\.",
                r"^rewards?\.",
                r"^member\.",
                r"^account\.",
                r"^billing\.",
                r"^team\.",
                r"^hello\.",
                r"^hi\.",
                r"^noreply\.",
                r"^no-reply\.",
                r"^donotreply\.",
            ],
            transactional_patterns=[
                r"\byour order\b",
                r"\border #\d+\b",
                r"\bconfirmation #\b",
                r"\breceipt\b",
                r"\binvoice\b",
                r"\bstatement\b",
                r"\btransaction\b",
                r"\bpurchase\b",
                r"\brefund\b",
                r"\breturn\b",
                r"\bexchange\b",
                r"\bshipped\b",
                r"\bout for delivery\b",
                r"\bdelivery scheduled\b",
                r"\bpackage (arrive|deliver)\b",
                r"\bverify your (email|account)\b",
                r"\breset your password\b",
                r"\bconfirm your (email|account)\b",
                r"\bactivate your account\b",
                r"\bsecurity (alert|code|verification)\b",
                r"\btwo-factor\b",
                r"\b2fa\b",
                r"\bverification code\b",
                r"\bone-time (password|code)\b",
                r"\botp\b",
                r"\blogin attempt\b",
                r"\bsign[- ]in (from|attempt)\b",
                r"\baccount (activity|update|change)\b",
                r"\bprivacy (policy|update)\b",
                r"\bterms of service\b",
                r"\bservice agreement\b",
            ],
            marketing_footer_patterns=[
                r"you('re| are) receiving this (email|message) because",
                r"this (email|message) was sent to",
                r"to (stop receiving|unsubscribe|opt[- ]out)",
                r"click here to unsubscribe",
                r"manage (your )?preferences",
                r"update (your )?(email )?preferences",
                r"view (this email )?in (your )?browser",
                r"add us to your (address book|contacts)",
                r"forward (this email )?to a friend",
                r"privacy policy",
                r"\u00a9 \d{4}",  # Copyright symbol followed by year
                r"all rights reserved",
            ],
        )

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "FilterRules":
        base = cls.default()
        for key, value in data.items():
            if hasattr(base, key):
                setattr(base, key, value)
        return base

    def to_dict(self) -> Dict[str, Any]:
        return {
            "job_source_domains": self.job_source_domains,
            "non_job_domains": self.non_job_domains,
            "job_keywords": self.job_keywords,
            "weak_job_keywords": self.weak_job_keywords,
            "role_title_patterns": self.role_title_patterns,
            "promo_negative_patterns": self.promo_negative_patterns,
            "edu_negative_patterns": self.edu_negative_patterns,
            "strong_job_signal_patterns": self.strong_job_signal_patterns,
            "interview_context_patterns": self.interview_context_patterns,
            "oa_assessment_patterns": self.oa_assessment_patterns,
            "promotional_sender_patterns": self.promotional_sender_patterns,
            "commercial_domain_patterns": self.commercial_domain_patterns,
            "transactional_patterns": self.transactional_patterns,
            "marketing_footer_patterns": self.marketing_footer_patterns,
        }


def load_rules(path: str | Path) -> FilterRules:
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    return FilterRules.from_dict(data)
